name: Node pnpm CI

on:
  push:
    branches:
      - "master" # match main branch
      - "dev" # match developer branch
      - "release/*" # matches release branch
      - "feature/*" # matches feature branch
      - "bugfix/*" # matches bugfix branch
      - "hotfix/*" # matches hotfix branch
      - "35-new-version" # temp match
  pull_request:
    branches:
      - "master" # match main branch
      - "dev" # match developer branch
      - "release/*" # matches release branch
      - "feature/*" # matches feature branch
      - "bugfix/*" # matches bugfix branch
      - "hotfix/*" # matches hotfix branch
      - "35-new-version" # temp match

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [16.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"
        env:
          CI: true
          PROGRESS: none
          NODE_ENV: test
          NODE_OPTIONS: --max_old_space_size=4096
      - name: pnpm install
        run: |
          echo ${{github.ref}}
          pnpm install
      - name: tools-site run cmd
        working-directory: ./apps/tools-site
        run: |
          echo ${{github.workspace}}
          pnpm run lint:error
          pnpm run tsc
          pnpm run build
