name: Deploy preview

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use nodejs build dist
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
        env:
          CI: true
          NETLIFY_AUTH_TOKEN: ${{ secrets.NSP_NETLIFY_ACCESS_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NSP_NETLIFY_PREVIEW_ID }}
        run: |
          echo ${{github.ref}}
          npm install -g pnpm
          pnpm config set store-dir ~/.pnpm-store
          pnpm install --strict-peer-dependencies=false
          pnpm run lint:error
          pnpm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: 'dist'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NSP_NETLIFY_ACCESS_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NSP_NETLIFY_PREVIEW_ID }}
        timeout-minutes: 1
