name: PUSH CHECK CI

on:
  push:
    branches:
      - "master" # match main branch
      - "dev" # match developer branch
      - "release/*" # matches release branch
      - "feature/*" # matches feature branch
      - "bugfix/*" # matches bugfix branch
      - "hotfix/*" # matches hotfix branch
      - "35-new-version" # temp match

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [16.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"
        env:
          CI: true
          PROGRESS: none
          NODE_ENV: test
          NODE_OPTIONS: --max_old_space_size=4096
      - name: pnpm install
        run: |
          echo ${{github.ref}}
          pnpm install
      - name: Check
        run: |
          echo ${{github.workspace}}
          pnpm --filter "./apps/**" --filter "./packages/**" lint:error
          pnpm --filter "./apps/**" --filter "./packages/**" tsc
          pnpm --filter "./apps/**" --filter "./packages/**" build
      - name: Comment success
        if: ${{ success() }}
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            ‚úÖ ${{ matrix.os }} actions success!
      - name: Comment failure
        if: ${{ failure() }}
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            ‚ùå ${{ matrix.os }} actions failure!
      - name: Comment cancelled
        if: ${{ cancelled() }}
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            üö´ ${{ matrix.os }} actions cancelled!
